---
name: commit

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches: [main]

jobs:
  no-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run test
        uses: NexusPHP/no-merge-commits@v2.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
