---
name: 'Lint YAML'
on:  # yamllint disable-line rule:truthy
  - pull_request
jobs:
  yamllint:
    name: 'Lint YAML'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_strict: true
          yamllint_comment: false
